// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FlightInfo.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Com.Variflight.Fidstest.Flight {
  public static partial class FlightService
  {
    static readonly string __ServiceName = "com.variflight.fidstest.flight.FlightService";

    static readonly grpc::Marshaller<global::Com.Variflight.Fidstest.Flight.Nothing> __Marshaller_com_variflight_fidstest_flight_Nothing = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Variflight.Fidstest.Flight.Nothing.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Com.Variflight.Fidstest.Flight.FlightList> __Marshaller_com_variflight_fidstest_flight_FlightList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Variflight.Fidstest.Flight.FlightList.Parser.ParseFrom);

    static readonly grpc::Method<global::Com.Variflight.Fidstest.Flight.Nothing, global::Com.Variflight.Fidstest.Flight.FlightList> __Method_PullFlightInfo = new grpc::Method<global::Com.Variflight.Fidstest.Flight.Nothing, global::Com.Variflight.Fidstest.Flight.FlightList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PullFlightInfo",
        __Marshaller_com_variflight_fidstest_flight_Nothing,
        __Marshaller_com_variflight_fidstest_flight_FlightList);

    static readonly grpc::Method<global::Com.Variflight.Fidstest.Flight.Nothing, global::Com.Variflight.Fidstest.Flight.Nothing> __Method_Stream = new grpc::Method<global::Com.Variflight.Fidstest.Flight.Nothing, global::Com.Variflight.Fidstest.Flight.Nothing>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Stream",
        __Marshaller_com_variflight_fidstest_flight_Nothing,
        __Marshaller_com_variflight_fidstest_flight_Nothing);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Com.Variflight.Fidstest.Flight.FlightInfoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FlightService</summary>
    [grpc::BindServiceMethod(typeof(FlightService), "BindService")]
    public abstract partial class FlightServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Com.Variflight.Fidstest.Flight.FlightList> PullFlightInfo(global::Com.Variflight.Fidstest.Flight.Nothing request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Stream(global::Com.Variflight.Fidstest.Flight.Nothing request, grpc::IServerStreamWriter<global::Com.Variflight.Fidstest.Flight.Nothing> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FlightService</summary>
    public partial class FlightServiceClient : grpc::ClientBase<FlightServiceClient>
    {
      /// <summary>Creates a new client for FlightService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FlightServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FlightService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FlightServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FlightServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FlightServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Com.Variflight.Fidstest.Flight.FlightList PullFlightInfo(global::Com.Variflight.Fidstest.Flight.Nothing request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PullFlightInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Com.Variflight.Fidstest.Flight.FlightList PullFlightInfo(global::Com.Variflight.Fidstest.Flight.Nothing request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PullFlightInfo, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Variflight.Fidstest.Flight.FlightList> PullFlightInfoAsync(global::Com.Variflight.Fidstest.Flight.Nothing request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PullFlightInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Variflight.Fidstest.Flight.FlightList> PullFlightInfoAsync(global::Com.Variflight.Fidstest.Flight.Nothing request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PullFlightInfo, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Com.Variflight.Fidstest.Flight.Nothing> Stream(global::Com.Variflight.Fidstest.Flight.Nothing request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Stream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Com.Variflight.Fidstest.Flight.Nothing> Stream(global::Com.Variflight.Fidstest.Flight.Nothing request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Stream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override FlightServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FlightServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(FlightServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PullFlightInfo, serviceImpl.PullFlightInfo)
          .AddMethod(__Method_Stream, serviceImpl.Stream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, FlightServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_PullFlightInfo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Com.Variflight.Fidstest.Flight.Nothing, global::Com.Variflight.Fidstest.Flight.FlightList>(serviceImpl.PullFlightInfo));
      serviceBinder.AddMethod(__Method_Stream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Com.Variflight.Fidstest.Flight.Nothing, global::Com.Variflight.Fidstest.Flight.Nothing>(serviceImpl.Stream));
    }

  }
}
#endregion
