// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestMessage.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Com.Variflight.Dataservice.Test {
  public static partial class ScoreService
  {
    static readonly string __ServiceName = "com.variflight.dataservice.test.ScoreService";

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Com.Variflight.Dataservice.Test.StudentScoresMap> __Marshaller_com_variflight_dataservice_test_StudentScoresMap = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Variflight.Dataservice.Test.StudentScoresMap.Parser.ParseFrom);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Variflight.Dataservice.Test.StudentScoresMap> __Method_GetAllScores = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Variflight.Dataservice.Test.StudentScoresMap>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllScores",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_com_variflight_dataservice_test_StudentScoresMap);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Com.Variflight.Dataservice.Test.TestMessageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ScoreService</summary>
    [grpc::BindServiceMethod(typeof(ScoreService), "BindService")]
    public abstract partial class ScoreServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Com.Variflight.Dataservice.Test.StudentScoresMap> GetAllScores(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ScoreService</summary>
    public partial class ScoreServiceClient : grpc::ClientBase<ScoreServiceClient>
    {
      /// <summary>Creates a new client for ScoreService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ScoreServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ScoreService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ScoreServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ScoreServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ScoreServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Com.Variflight.Dataservice.Test.StudentScoresMap GetAllScores(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllScores(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Com.Variflight.Dataservice.Test.StudentScoresMap GetAllScores(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllScores, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Variflight.Dataservice.Test.StudentScoresMap> GetAllScoresAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllScoresAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Variflight.Dataservice.Test.StudentScoresMap> GetAllScoresAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllScores, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ScoreServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ScoreServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ScoreServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllScores, serviceImpl.GetAllScores).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ScoreServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAllScores, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Variflight.Dataservice.Test.StudentScoresMap>(serviceImpl.GetAllScores));
    }

  }
}
#endregion
